### ISSUE TITLE
background renk değişimi

### ISSUE THREAD

**Issue by NisanurBulut** [ysfzun/Mustang-Modal#1]
merhabai background renk değişimi yapılabiliyor mu ? evetse nasıl olduğu konusunda yardımcı olur musunuz ?

**Comment by ysfzun** [comment]
Merhaba, biraz geç bir cevap olacak. :)

Backgruund değişimini CSS ile yapabilirsiniz. İhtiyacınıza göre ".mustang-modal-container" ya da ".mustang-modal" classlarını inceleyebilirsiniz. Bunun dışında ihtiyacınız olan şeyi tam olarak yazarsanız yardımcı olabilirim.
